# config for analysis

# most CPUs to ever use at once
max_cpus: 16

# do we get the sequencing data from locally on our server versus SRA?
seqdata_source: local

# list of Illumina sequencing runs of barcodes
barcode_runs_Wuhan_Hu_1: data/barcode_runs_Wuhan_Hu_1.csv
barcode_runs_Omicron_BA2: data/barcode_runs_Omicron_BA2.csv
barcode_runs_Omicron_BQ11: data/barcode_runs_Omicron_BQ11.csv
barcode_runs_Omicron_XBB15: data/barcode_runs_Omicron_XBB15.csv

barcode_runs_Omicron_EG5: data/barcode_runs_Omicron_EG5.csv
barcode_runs_Omicron_FLip: data/barcode_runs_Omicron_FLip.csv
barcode_runs_Omicron_BA286: data/barcode_runs_Omicron_BA286.csv


# table of barcode-variant lookups for different libraries
bc_variant_lookup_Wuhan_Hu_1: data/codon_variant_table_Wuhan_Hu_1.csv
bc_variant_lookup_Omicron_BA2: data/codon_variant_table_Omicron_BA2.csv
bc_variant_lookup_Omicron_BQ11: data/codon_variant_table_Omicron_BQ11.csv
bc_variant_lookup_Omicron_XBB15: data/codon_variant_table_Omicron_XBB15.csv

bc_variant_lookup_Omicron_EG5: data/codon_variant_table_Omicron_EG5.csv
bc_variant_lookup_Omicron_FLip: data/codon_variant_table_Omicron_FLip.csv
bc_variant_lookup_Omicron_BA286: data/codon_variant_table_Omicron_BA286.csv

# sequencing counts to cells ratio should exceed this for escape samples
min_counts_to_cells_ratio: 2.5
# sequencing counts should exceed this for reference samples
reference_min_counts: 2.5e+7

# wildtype sequence of mutagenized gene
wildtype_sequence_Wuhan_Hu_1: data/wildtype_sequence_Wuhan_Hu_1.fasta
wildtype_sequence_Omicron_BA2: data/wildtype_sequence_Omicron_BA2.fasta
wildtype_sequence_Omicron_BQ11: data/wildtype_sequence_Omicron_BQ11.fasta
wildtype_sequence_Omicron_XBB15: data/wildtype_sequence_Omicron_XBB15.fasta

wildtype_sequence_Omicron_EG5: data/wildtype_sequence_Omicron_EG5.fasta
wildtype_sequence_Omicron_FLip: data/wildtype_sequence_Omicron_FLip.fasta
wildtype_sequence_Omicron_BA286: data/wildtype_sequence_Omicron_BA286.fasta

RBD_sequence_Omicron_BA2: data/RBD_BA2_seq.fasta
site_number_offset: 330  # add this to sequential sites to get RBD numbering in WH1

# URLs from which we download binding & expression of mutants & variants
mut_bind_expr_url: https://media.githubusercontent.com/media/tstarrlab/SARS-CoV-2-RBD_DMS_Omicron-EG5-FLip-BA286/main/results/final_variant_scores/final_variant_scores.csv?token=ABECTFKXK3VN2TLUYYV3743GFGVUM
early2020_mut_bind_expr_url: https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS/master/results/single_mut_effects/single_mut_effects.csv


# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GCTCGCGGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0

# Input files for analyses from the data subdirectory
RBD_sites: data/RBD_sites.csv

# Parameters used when computed escape scores:
escape_score_type: frac_escape  # type of escape score, see dms_variants
escape_score_pseudocount: 0.5  # added to observed counts
escape_score_floor_E: 0  # floor on escape fractions
escape_score_ceil_E: 1  # ceiling on escape fractions
# Group variants by this when calculating escape scores; sensible values are
# "barcode" (to calculate a score for each barcoded variant) or
# "aa_substitutions" (to group all variants with same amino-acid substitutions):
escape_score_group_by: barcode
# Filter variants (after grouping according to `escape_group_by`) with
# pre-selection counts < this quantile of stop codon variants, thereby
# removing low count "noise":
escape_score_precount_filter: 100
# Filter variants with mutation with binding or expression scores
# <= these values
escape_score_min_bind_mut_Wuhan_Hu_1: -3.0
escape_score_min_expr_mut_Wuhan_Hu_1: -1.25
escape_score_min_bind_mut_Omicron_BA2: -3.0
escape_score_min_expr_mut_Omicron_BA2: -0.955
escape_score_min_bind_mut_Omicron_BQ11: -3.0
escape_score_min_expr_mut_Omicron_BQ11: -1.229
escape_score_min_bind_mut_Omicron_XBB15: -3.0
escape_score_min_expr_mut_Omicron_XBB15: -1.25

escape_score_min_bind_mut_Omicron_BA286: -3.0
escape_score_min_expr_mut_Omicron_BA286: -1
escape_score_min_bind_mut_Omicron_EG5: -3.0
escape_score_min_expr_mut_Omicron_EG5: -1
escape_score_min_bind_mut_Omicron_FLip: -3.0
escape_score_min_expr_mut_Omicron_FLip: -1

#for YlOrBr scaling of bind phenotype, what should be the floor where YlOrBr reaches its minimum yellow coloring?
escape_score_bind_Yl_threshold: -2

# should we just exclude all mutations to sites where the WT is a cysteine?
exclude_cysteines: True
# Only retain mutation-level escape fraction estimates when there are
# **either** >= the indicated number of filtered variants (after grouping
# according to `escape_group_by`) with the mutation as a single mutant
# or in any context for that library:
escape_frac_min_single_mut_measurements: 2
escape_frac_min_any_mut_measurements: 2
# In order to compute an "average" escape fraction for a mutation, require
# it to be in at least this many libraries **or** to be observed at
# least this many total times as a single mutant across all libraries:
escape_frac_avg_min_libraries: 2
escape_frac_avg_min_single: 2

# Parameters in escape frac output file that enable dms-view
# visualization on PDB 6m0j:
escape_frac_protein_chain: E  # use this chain


# Parameters for calling sites of strong escape based on site escape metric.
# There are several different calling thresholds defined. In order to be called,
# a site must meet *all* of the site criteria or have a mutation that meets
# *all* of the mutation criteria.
strong_escape_sites_calling_params:
  default:
    exceed_median: 10  # must exceed median across sites by > this
    frac_max: 0.1  # must be > this much of max escape site
    min_value: 0  # site selection must be > than this
  sensitive:
    exceed_median: 5  # must exceed median across sites by > this
    frac_max: 0.05  # must be > this much of max escape site
    min_value: 0  # must be > than this
  sensitive_max_mut:
    exceed_median: 5  # must exceed median across sites by > this
    frac_max: 0.05  # must be > this much of max escape site
    min_value: 0  # must be > than this
    min_value_mut: 0.5  # keep site if any mutation selection > than this

# Site- and mutation-level metrics for escape profiles
site_metric: site_total_escape_frac_single_mut
mut_metric: mut_escape_frac_single_mut
# Specify how to plot escape profiles
escape_profiles_config_Wuhan_Hu_1: data/escape_profiles_config_Wuhan_Hu_1.yaml
escape_profiles_config_Omicron_BA2: data/escape_profiles_config_Omicron_BA2.yaml
escape_profiles_config_Omicron_BQ11: data/escape_profiles_config_Omicron_BQ11.yaml
escape_profiles_config_Omicron_XBB15: data/escape_profiles_config_Omicron_XBB15.yaml

escape_profiles_config_Omicron_EG5: data/escape_profiles_config_Omicron_EG5.yaml
escape_profiles_config_Omicron_FLip: data/escape_profiles_config_Omicron_FLip.yaml
escape_profiles_config_Omicron_BA286: data/escape_profiles_config_Omicron_BA286.yaml
# Site color schemes for escape profiles
site_color_schemes: data/site_color_schemes.csv
# Set default y-axis max for escape profiles. The y-axis ymax is
# scaled to larger of max site escape for antibody / sera **or** so
# indicated quantile of site escape is at the indicated fraction of y-axis
# height. It's also possible to set a minimum value for the y-maximum.
# See: https://jbloomlab.github.io/dmslogo/set_ylims.html. Can be
# overridden for specific escape profiles in `data/escape_profiles_config.yaml`.
escape_profile_ymax:
  quantile: 0.5
  frac: 0.05
  min_ymax: null

# structural mappings configuration
output_pdbs_config: data/output_pdbs_config_Wuhan_Hu_1.yaml
output_pdbs_config_BA2: data/output_pdbs_config_Omicron_BA2.yaml
output_pdbs_config_BQ11: data/output_pdbs_config_Omicron_BQ11.yaml
output_pdbs_config_XBB15: data/output_pdbs_config_Omicron_XBB15.yaml

output_pdbs_config_EG5: data/output_pdbs_config_Omicron_EG5.yaml
output_pdbs_config_FLip: data/output_pdbs_config_Omicron_FLip.yaml
output_pdbs_config_BA286: data/output_pdbs_config_Omicron_BA286.yaml

# escape selection results
escape_selection_results: data/escape_selection_results.yaml

# output directories / files
summary_dir: results/summary
figs_dir: results/figures

#downloaded prior dms measures
mut_bind_expr: results/prior_DMS_data/mutant_ACE2binding_expression.csv
early2020_mut_bind_expr: results/prior_DMS_data/early2020_mutant_ACE2binding_expression.csv

#output dirs and files for current analyses
counts_dir_Wuhan_Hu_1: results/counts/Wuhan_Hu_1
counts_dir_Omicron_BA2: results/counts/Omicron_BA2
counts_dir_Omicron_BQ11: results/counts/Omicron_BQ11
counts_dir_Omicron_XBB15: results/counts/Omicron_XBB15

counts_dir_Omicron_EG5: results/counts/Omicron_EG5
counts_dir_Omicron_FLip: results/counts/Omicron_FLip
counts_dir_Omicron_BA286: results/counts/Omicron_BA286

variant_counts_Wuhan_Hu_1: results/counts/Wuhan_Hu_1/variant_counts.csv.gz
variant_counts_Omicron_BA2: results/counts/Omicron_BA2/variant_counts.csv.gz
variant_counts_Omicron_BQ11: results/counts/Omicron_BQ11/variant_counts.csv.gz
variant_counts_Omicron_XBB15: results/counts/Omicron_XBB15/variant_counts.csv.gz

variant_counts_Omicron_EG5: results/counts/Omicron_EG5/variant_counts.csv.gz
variant_counts_Omicron_FLip: results/counts/Omicron_FLip/variant_counts.csv.gz
variant_counts_Omicron_BA286: results/counts/Omicron_BA286/variant_counts.csv.gz

counts_to_cells_csv_Wuhan_Hu_1: results/counts/Wuhan_Hu_1/counts_to_cells_csv.csv
counts_to_cells_csv_Omicron_BA2: results/counts/Omicron_BA2/counts_to_cells_csv.csv
counts_to_cells_csv_Omicron_BQ11: results/counts/Omicron_BQ11/counts_to_cells_csv.csv
counts_to_cells_csv_Omicron_XBB15: results/counts/Omicron_XBB15/counts_to_cells_csv.csv

counts_to_cells_csv_Omicron_EG5: results/counts/Omicron_EG5/counts_to_cells_csv.csv
counts_to_cells_csv_Omicron_FLip: results/counts/Omicron_FLip/counts_to_cells_csv.csv
counts_to_cells_csv_Omicron_BA286: results/counts/Omicron_BA286/counts_to_cells_csv.csv

escape_scores_dir: results/escape_scores

escape_score_samples_Wuhan_Hu_1: results/escape_scores/samples_Wuhan_Hu_1.csv
escape_score_samples_Omicron_BA2: results/escape_scores/samples_Omicron_BA2.csv
escape_score_samples_Omicron_BQ11: results/escape_scores/samples_Omicron_BQ11.csv
escape_score_samples_Omicron_XBB15: results/escape_scores/samples_Omicron_XBB15.csv

escape_score_samples_Omicron_EG5: results/escape_scores/samples_Omicron_EG5.csv
escape_score_samples_Omicron_FLip: results/escape_scores/samples_Omicron_FLip.csv
escape_score_samples_Omicron_BA286: results/escape_scores/samples_Omicron_BA286.csv

escape_scores_Wuhan_Hu_1: results/escape_scores/scores_Wuhan_Hu_1.csv
escape_scores_Omicron_BA2: results/escape_scores/scores_Omicron_BA2.csv
escape_scores_Omicron_BQ11: results/escape_scores/scores_Omicron_BQ11.csv
escape_scores_Omicron_XBB15: results/escape_scores/scores_Omicron_XBB15.csv

escape_scores_Omicron_EG5: results/escape_scores/scores_Omicron_EG5.csv
escape_scores_Omicron_FLip: results/escape_scores/scores_Omicron_FLip.csv
escape_scores_Omicron_BA286: results/escape_scores/scores_Omicron_BA286.csv

escape_fracs_Wuhan_Hu_1: results/escape_scores/escape_fracs_Wuhan_Hu_1.csv
escape_fracs_Omicron_BA2: results/escape_scores/escape_fracs_Omicron_BA2.csv
escape_fracs_Omicron_BQ11: results/escape_scores/escape_fracs_Omicron_BQ11.csv
escape_fracs_Omicron_XBB15: results/escape_scores/escape_fracs_Omicron_XBB15.csv

escape_fracs_Omicron_EG5: results/escape_scores/escape_fracs_Omicron_EG5.csv
escape_fracs_Omicron_FLip: results/escape_scores/escape_fracs_Omicron_FLip.csv
escape_fracs_Omicron_BA286: results/escape_scores/escape_fracs_Omicron_BA286.csv

escape_profiles_dms_colors_Wuhan_Hu_1: results/escape_profiles/Wuhan_Hu_1/escape_profiles_dms_colors.csv
escape_profiles_dms_colors_Omicron_BA2: results/escape_profiles/Omicron_BA2/escape_profiles_dms_colors.csv
escape_profiles_dms_colors_Omicron_BQ11: results/escape_profiles/Omicron_BQ11/escape_profiles_dms_colors.csv
escape_profiles_dms_colors_Omicron_XBB15: results/escape_profiles/Omicron_XBB15/escape_profiles_dms_colors.csv

escape_profiles_dms_colors_Omicron_EG5: results/escape_profiles/Omicron_EG5/escape_profiles_dms_colors.csv
escape_profiles_dms_colors_Omicron_FLip: results/escape_profiles/Omicron_FLip/escape_profiles_dms_colors.csv
escape_profiles_dms_colors_Omicron_BA286: results/escape_profiles/Omicron_BA286/escape_profiles_dms_colors.csv

escape_profiles_dir_Wuhan_Hu_1: results/escape_profiles/Wuhan_Hu_1
escape_profiles_dir_Omicron_BA2: results/escape_profiles/Omicron_BA2
escape_profiles_dir_Omicron_BQ11: results/escape_profiles/Omicron_BQ11
escape_profiles_dir_Omicron_XBB15: results/escape_profiles/Omicron_XBB15

escape_profiles_dir_Omicron_EG5: results/escape_profiles/Omicron_EG5
escape_profiles_dir_Omicron_FLip: results/escape_profiles/Omicron_FLip
escape_profiles_dir_Omicron_BA286: results/escape_profiles/Omicron_BA286

strong_escape_sites_Wuhan_Hu_1: results/escape_profiles/strong_escape_sites_Wuhan_Hu_1.csv
strong_escape_sites_Omicron_BA2: results/escape_profiles/strong_escape_sites_Omicron_BA2.csv
strong_escape_sites_Omicron_BQ11: results/escape_profiles/strong_escape_sites_Omicron_BQ11.csv
strong_escape_sites_Omicron_XBB15: results/escape_profiles/strong_escape_sites_Omicron_XBB15.csv

strong_escape_sites_Omicron_EG5: results/escape_profiles/strong_escape_sites_Omicron_EG5.csv
strong_escape_sites_Omicron_FLip: results/escape_profiles/strong_escape_sites_Omicron_FLip.csv
strong_escape_sites_Omicron_BA286: results/escape_profiles/strong_escape_sites_Omicron_BA286.csv

pdb_outputs_dir_Wuhan_Hu_1: results/pdb_outputs/Wuhan_Hu_1
pdb_outputs_dir_Omicron_BA2: results/pdb_outputs/Omicron_BA2
pdb_outputs_dir_Omicron_BQ11: results/pdb_outputs/Omicron_BQ11
pdb_outputs_dir_Omicron_XBB15: results/pdb_outputs/Omicron_XBB15

pdb_outputs_dir_Omicron_EG5: results/pdb_outputs/Omicron_EG5
pdb_outputs_dir_Omicron_FLip: results/pdb_outputs/Omicron_FLip
pdb_outputs_dir_Omicron_BA286: results/pdb_outputs/Omicron_BA286

supp_data_dir_Wuhan_Hu_1: results/supp_data/Wuhan_Hu_1
supp_data_dir_Omicron_BA2: results/supp_data/Omicron_BA2
supp_data_dir_Omicron_BQ11: results/supp_data/Omicron_BQ11
supp_data_dir_Omicron_XBB15: results/supp_data/Omicron_XBB15

supp_data_dir_Omicron_EG5: results/supp_data/Omicron_EG5
supp_data_dir_Omicron_FLip: results/supp_data/Omicron_FLip
supp_data_dir_Omicron_BA286: results/supp_data/Omicron_BA286

bind_expr_filters_dir_Wuhan_Hu_1: results/bind_expr_filters/Wuhan_Hu_1
bind_expr_filters_dir_Omicron_BA2: results/bind_expr_filters/Omicron_BA2
bind_expr_filters_dir_Omicron_BQ11: results/bind_expr_filters/Omicron_BQ11
bind_expr_filters_dir_Omicron_XBB15: results/bind_expr_filters/Omicron_XBB15

bind_expr_filters_dir_Omicron_EG5: results/bind_expr_filters/Omicron_EG5
bind_expr_filters_dir_Omicron_FLip: results/bind_expr_filters/Omicron_FLip
bind_expr_filters_dir_Omicron_BA286: results/bind_expr_filters/Omicron_BA286

escape_selections_dir: results/escape_selections

gisaid_mutations_dir: results/GISAID_mutations
spike_sequences: results/GISAID_mutations/spike_sequences.fasta
rbd_alignment: results/GISAID_mutations/RBD_alignment.fasta
gisaid_mutation_counts: results/GISAID_mutations/mutation_counts.csv
gisaid_mutation_counts_old: data/GISAID_mutation_counts.csv

custom_plots_dir: results/custom_plots
